---
default_stages:
  - pre-commit
fail_fast: true

repos:
  # 1. Python checks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  # 2. YAML checks
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  # 3. Check gitleaks for secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - name: Gitleaks
        id: gitleaks-docker
        args: ["--verbose", "--redact"]
        files: .*

  # 4. General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
