services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
