apiVersion: v1
kind: Service
metadata:
  name: {{ include "list-books-helm.name" . }}
  labels:
    {{- include "list-books-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: {{ .Values.frontend.service.protocol }}
  selector:
    {{- include "list-books-helm.selectorLabels" . | nindent 4 }}
