apiVersion: v1
kind: Service
metadata:
  name: {{ include "list-books-helm.name" . }}
  labels:
    {{- include "list-books-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: http
  selector:
    {{- include "list-books-helm.selectorLabels" . | nindent 4 }}
    app: {{ .Values.database.name }}
