---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
spec:
  {{- range .Values.database.pvc.accessModes }}
  accessModes:
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
