---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- if .Values.secrets.enabled }}
    {{- range $key, $val := .Values.secrets.data }}
        {{- $key }}: {{ $val | b64enc }}
    {{- end -}}
    {{- if .Values.secrets.data.github.enabled }}
      GITHUB_TOKEN: {{ .Values.secrets.data.github.token | b64enc }}
    {{- end -}}
  {{ end -}}
